CREATE TABLE USER (
	id INT NOT NULL,
	username VARCHAR(50) NOT NULL,
	password VARCHAR(100) NOT NULL,
	PRIMARY KEY (id),
	UNIQUE INDEX username (username)
)
COMMENT='tabla de usuarios de sistema'
COLLATE='latin1_spanish_ci'
;

#crear una tabla
CREATE TABLE ROL (
	id INT NOT NULL,
	ROLE VARCHAR(50) NOT NULL 
);

#agregar constraint
ALTER TABLE ROL ADD CONSTRAINT PRIMARY KEY (ID);
ALTER TABLE ROL ADD CONSTRAINT UNIQUE FK_ROL_ROLE(ROLE);
ALTER TABLE ROL CHANGE COLUMN id id INT(10) NOT NULL AUTO_INCREMENT FIRST;
ALTER TABLE USER CHANGE COLUMN id id INT(10) NOT NULL AUTO_INCREMENT FIRST;

#eliminar una tabla
#DROP TABLE ROL;
#DROP TABLE USER;

CREATE TABLE USERS_ROLES (
	user_id INT NOT NULL,
	rol_id INT NOT NULL
);

#DROP TABLE USERS_ROLES;
ALTER TABLE USERS_ROLES ADD CONSTRAINT PRIMARY KEY (user_id,rol_id);
ALTER TABLE USERS_ROLES ADD CONSTRAINT FK_USERS_ROLES_USER FOREIGN KEY (user_id) REFERENCES USER (id);
ALTER TABLE USERS_ROLES ADD CONSTRAINT FK_USERS_ROLES_ROL FOREIGN KEY (rol_id) REFERENCES ROL (id);

#ROMPO LA CONSTRAINT ENTRE USER_ROLES Y USER
#ALTER TABLE USERS_ROLES DROP CONSTRAINT FK_USERS_ROLES_USER


#AGREGAR DATOS A LAS TABLAS
INSERT INTO ROL (ROLE) VALUES ('USER');
INSERT INTO ROL (ROLE) VALUES ('ADMIN');
INSERT INTO ROL (ROLE) VALUES ('OFICIAL');

#EN USER
INSERT INTO USER (username,PASSWORD) VALUES('administrador', '$2y$10$psA9TCXiMrvJcJrSCwie/.YlaJRJyZ7aOVuSgPEmrZSogGcLczFnm');
INSERT INTO USER (username,PASSWORD) VALUES('usuario', '$2y$10$psA9TCXiMrvJcJrSCwie/.YlaJRJyZ7aOVuSgPEmrZSogGcLczFnm');
INSERT INTO USER (username,PASSWORD) VALUES('oficial', '$2y$10$psA9TCXiMrvJcJrSCwie/.YlaJRJyZ7aOVuSgPEmrZSogGcLczFnm');

# LA TABLA DE MUCHOS A MUCHOS
INSERT INTO USERS_ROLES (user_id,rol_id) values(1,2);
INSERT INTO USERS_ROLES (user_id,rol_id) values(2,1);
INSERT INTO USERS_ROLES (user_id,rol_id) values(3,3);